#!/bin/sh
if [ "`grep -i splash /proc/cmdline`" ]; then
  case "$1" in
      start)
         cat /usr/share/shr-splash/boot.fb > /dev/fb0 &
      ;;
      stop)
         cat /usr/share/shr-splash/shutdown.fb > /dev/fb0 &
      ;;
  esac
fi

exit 0
